#!/usr/bin/env node
// Regenerates the typed database schema used by the API from the local database.
import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const result = spawnSync('npx', ['supabase', 'gen', 'types', '--lang', 'typescript', '--local'], {
  cwd: root,
  encoding: 'utf8',
  shell: process.platform === 'win32',
});
if (result.status !== 0) {
  process.stderr.write(result.stderr);
  process.exit(result.status ?? 1);
}
const target = path.join(root, 'apps/api/src/database.types.ts');
writeFileSync(target, `// Generated by \`npm run db:types\`. Do not edit.\n${result.stdout}`);
console.log(`wrote ${path.relative(root, target)}`);
